version: '3.3'

services:
  # dbsql:
  #   image: mysql:8.0.32
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_DATABASE: ${DB_NAME}
  #   healthcheck:
  #     test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
  #     timeout: 20s
  #     retries: 10

  #   ports:
  #     - '3306:3306'
  #   expose:
  #     - '3306'
  #   volumes:
  #     - aircast:/var/lib/mysql

  redis-server:
    image: redis:latest
    ports:
      - '6379:6379'
    expose:
      - '6379'
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      redis-server:
        condition: service_healthy

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - '8501:8501'
    depends_on:
      - backend

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  aircast: